vs = '''
attribute vec4 in_position;
attribute vec2 in_texcoord;
attribute vec4 in_color;

varying vec2 vtx_texcoord;
varying vec4 vtx_color;

uniform mat4 mvp;

void main() {
	gl_Position = mvp * vec4(in_position.xyz, 1.0);
	vtx_texcoord = in_texcoord;
	vtx_color = in_color;
}
'''

ps = '''
varying mediump vec2 vtx_texcoord;
varying mediump vec4 vtx_color;

uniform sampler2D mainTexture;

void main() {
	gl_FragColor = texture2D(mainTexture, vtx_texcoord) * vtx_color * vec4(2.0, 2.0, 2.0, 1.0);
}
'''
